# Generated by Django 4.1.13 on 2024-05-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_film_rating_delete_category_delete_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="certificate",
            field=models.CharField(
                choices=[
                    ("U", "U"),
                    ("PG", "PG"),
                    ("12a", "12a"),
                    ("15", "15"),
                    ("18", "18"),
                ],
                max_length=3,
            ),
        ),
    ]
