# Generated by Django 4.1.13 on 2024-05-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_film_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="poster",
            field=models.CharField(max_length=100),
        ),
    ]
