# Generated by Django 4.1.13 on 2024-05-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_alter_film_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="ımbd_rating",
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="film",
            name="poster",
            field=models.URLField(max_length=100),
        ),
    ]
