# Generated by Django 4.1.13 on 2024-05-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_film_ımbd_rating_alter_film_poster"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="film",
            name="ımbd_rating",
        ),
        migrations.AddField(
            model_name="film",
            name="rat",
            field=models.DecimalField(decimal_places=2, default="exit", max_digits=2),
            preserve_default=False,
        ),
    ]
