# Generated by Django 4.1.13 on 2024-05-15 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_remove_film_rat_film_rati"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="film",
            name="rati",
        ),
    ]
